package com.ciot.base.constant;

public class AppConstant {
    public static final String ADMIN_PASSWORD = "007";
    public static final String BUNDLE_NAME_COMMAND_TYPE = "CommandType";
    public static final String BUNDLE_NAME_GUIDE = "Guide";
    public static final String BUNDLE_NAME_POINT_BEAN_INDEX = "PointBeanIndex";
    public static final String BUNDLE_NAME_ROBOTTASK = "RobotTask";
    public static final String BUNDLE_NAME_WAIT_BEAN = "WaitBean";
    public static final int CLICK_INTERVAL_TIME = 1000;
    public static final int DEBOUNCE_TIME = 1000;
    public static final String DEFAULT_TRANSPORT_PASSWORD = "8888";
    public static final String DEFAULT_VOICE_NAME = "xiaoyan";
    public static final int HIDDEN_FUNCTION_CLICK_TIMES = 6;
    public static volatile float HK_TEMPERATURE_THRESHOLD = 37.3f;
    public static final float HK_TEMPERATURE_THRESHOLD_MAX = 45.0f;
    public static final float HK_TEMPERATURE_THRESHOLD_MIN = 0.0f;
    public static final boolean IS_PHONE = false;
    public static final String MODULE_TAG = "NETWORK_TAG";
    public static final String ROBOT_BOOT_UP_TIPS = "机器人系统启动成功";
    public static final String ROBOT_MODULE = "SSR";
    public static final String ROBOT_NUMBER = "";
    public static final int ROBOT_TYPE = 6;
    public static final String SEPARATOR = "/";
    public static final int SPRAY_GEAR_NORMAL = 1;
    public static final int SPRAY_GEAR_THREE = 2;
    public static final String SP_ASR_FLAG = "AsrFlag";
    public static final String SP_CHASSIS_BOOT_HINT_FLAG = "ChassisBootHintFlag";
    public static final String SP_MOVE_FLAG = "MoveFlag";
    public static final String SP_SLEEP_FLAG = "SleepFlag";
    public static final String SP_VOICE_FLAG = "VoiceFlag";
    public static final String SP_WATER_CHASSIS_IDLE_TIME_BACK_CHARGING_PILE_FLAG = "WaterChassisIdleTimeBackChargingPileFlag";
    public static final String SP_WATER_CHASSIS_LOW_POWER_BACK_CHARGING_PILE_FLAG = "WaterChassisLowPowBackChargingPileFlag";
    public static final String TEMP_PATH = "/storage/emulated/0/KeepAlive";
    public static final String WATER_DEFAULT_ADMIN_PASSWORD = "86926868";
    public static final String WATER_DEFAULT_OPERATOR_PASSWORD = "123456";
    public static final String WATER_DEFAULT_SUPER_ADMIN_PASSWORD = "86926868";
    public static final int WATER_GET_ROBOT_STATUS_INTERVAL_TIME = 500;
    public static final int WATER_IDLE_TIME_BACK_CHARGING_PILE_DEFAULT_TIME = 5;
    public static final int WATER_IDLE_TIME_BACK_CHARGING_PILE_MAX_TIME = 99;
    public static final int WATER_LOW_POWER_WARING_VALUE = 20;
}
