package com.ciot.waterchassis;

import android.os.Environment;
import com.ciot.base.constant.FileConstant;
import io.reactivex.annotations.SchedulerSupport;
import java.io.File;
import mc.csst.com.selfchassis.ui.fragment.set.schedule.ScheduleFragment;

public class WaterChassisConstants {
    public static final int CALL_ELEVATOR_MARKER_TYPE = 3;
    public static final int CHARGE_MARKER_TYPE = 11;
    public static final String MSG_STATUS_INVALID_REQUEST = "INVALID_REQUEST";
    public static final String MSG_STATUS_OK = "OK";
    public static final String MSG_STATUS_REQUEST_DENIED = "REQUEST_DENIED";
    public static final String MSG_STATUS_UNKNOWN_ERROR = "UNKNOWN_ERROR";
    public static final int NORMAL_MARKER_TYPE = 0;
    public static final int TAKE_ELEVATOR_MARKER_TYPE = 4;
    public static final String WATER_ADJUST_POSITION = "/api/position_adjust";
    public static final String WATER_ADJUST_POSITION_BY_POSE = "/api/position_adjust_by_pose";
    public static final String WATER_CANCEL_MOVE = "/api/move/cancel";
    public static final String WATER_CHASSIS_IP = "192.168.10.10";
    public static final int WATER_CHASSIS_PORT = 31001;
    public static final String WATER_CHECK_UPDATE = "/api/software/check_for_update";
    public static final String WATER_CODE_AUTO_DOCK_CHARGING_PILE_FAIL = "01022";
    public static final String WATER_CODE_AUTO_DOCK_CHARGING_PILE_FAIL1 = "01023";
    public static final String WATER_CODE_AUTO_DOCK_CHARGING_PILE_FAIL2 = "01024";
    public static final String WATER_CODE_AUTO_DOCK_CHARGING_PILE_FAIL3 = "01025";
    public static final String WATER_CODE_AUTO_DOCK_CHARGING_PILE_FAIL4 = "01026";
    public static final String WATER_CODE_AVOID_LIFT = "04040";
    public static final String WATER_CODE_BACK_LIFT_FAIL = "04062";
    public static final String WATER_CODE_BACK_LIFT_SUCCESS = "04061";
    public static final String WATER_CODE_CALL_LIFT_MORE_THAN_TREE_MINUTES = "04013";
    public static final String WATER_CODE_CALL_LIFT_SUCCESS = "04011";
    public static final String WATER_CODE_CRUISE_FAILED = "01103";
    public static final String WATER_CODE_DOCK_CHARGING_PILE_SUCCESS = "01021";
    public static final String WATER_CODE_END_WAITING_FOR_THE_LIFT_TO_UNLOCK = "04071";
    public static final String WATER_CODE_ENTER_LIFT_SUCCESS = "04031";
    public static final String WATER_CODE_EXIT_LIFT_FAIL = "04052";
    public static final String WATER_CODE_EXIT_LIFT_SUCCESS = "04051";
    public static final String WATER_CODE_FAIL_ENTER_LIFT = "04032";
    public static final String WATER_CODE_GO_TO_LIFT_FAILED = "04002";
    public static final String WATER_CODE_GO_TO_LIFT_SUCCESS = "04001";
    public static final String WATER_CODE_LEAVE_CHARGING_PILE = "01010";
    public static final String WATER_CODE_LEAVE_CHARGING_PILE_FAIL = "01012";
    public static final String WATER_CODE_LEAVE_CHARGING_PILE_SUCCESS = "01011";
    public static final String WATER_CODE_MAKE_GLOBAL_PLAN_FAIL = "01203";
    public static final String WATER_CODE_MOVEMENT_OBSTRUCTE = "01200";
    public static final String WATER_CODE_MOVE_TASK_CANCEL = "01004";
    public static final String WATER_CODE_MOVE_TASK_FAIL = "01003";
    public static final String WATER_CODE_MOVE_TASK_FINISH = "01002";
    public static final String WATER_CODE_MOVE_TASK_RETRY = "01005";
    public static final String WATER_CODE_MOVE_TASK_START = "01001";
    public static final String WATER_CODE_MOVE_TASK_TRAP = "01006";
    public static final String WATER_CODE_NOT_ENOUGH_SPACE = "04033";
    public static final String WATER_CODE_NO_PATH_AVAILABLE = "01007";
    public static final String WATER_CODE_ROBOT_MAYBE_LOST = "02010";
    public static final String WATER_CODE_START_BACK_LIFT = "04060";
    public static final String WATER_CODE_START_CALL_LIFT = "04010";
    public static final String WATER_CODE_START_EXIT_LIFT = "04050";
    public static final String WATER_CODE_START_GO_TO_LIFT = "04000";
    public static final String WATER_CODE_START_TO_ENTER_IFT = "04030";
    public static final String WATER_CODE_START_WAITING_FOR_THE_LIFT_TO_UNLOCK = "04070";
    public static final String WATER_CODE_TAKE_LIFT_MORE_THAN_TREE_MINUTES = "04023";
    public static final String WATER_CODE_TAKE_LIFT_SUCCESS = "04021";
    public static final String WATER_CODE_TRAPPED_IN_OBSTACLE = "01202";
    public static final String WATER_CODE_TRAPPED_IN_UNKNOWN_AREA = "01201";
    public static final String WATER_DELETE_MARKER = "/api/markers/delete";
    public static final String WATER_ESTOP = "/api/estop";
    public static final String WATER_GET_BRIDGE_STATUS = "/api/router/get_bridge_status";
    public static final String WATER_GET_CURRENT_MAP = "/api/map/get_current_map";
    public static final String WATER_GET_DIAGNOSIS_RESULT = "/api/diagnosis/get_result";
    public static final String WATER_GET_MAP_LIST = "/api/map/list";
    public static final String WATER_GET_PARAMS = "/api/get_params";
    public static final int WATER_GET_ROBOT_STATUS_INTERVAL_TIME = 800;
    public static final String WATER_GET_SOFTWARE_VERSION = "/api/software/get_version";
    public static final String WATER_HOTSPOT_CONFIG = "/api/router/hotspot_config";
    public static final String WATER_INSERT_MARKER = "/api/markers/insert";
    public static final String WATER_INSERT_MARKER_BY_POSE = "/api/markers/insert_by_pose";
    public static final String WATER_JOY_CONTROL = "/api/joy_control";
    public static final String WATER_MAIN_CONTROL_APK_FILE_PATH;
    public static final String WATER_MAIN_CONTROL_CUSTOM_FILE_NAME = "robotInfo.txt";
    public static final String WATER_MAIN_CONTROL_CUSTOM_FILE_PATH = (Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "MainControl" + File.separator + SchedulerSupport.CUSTOM + File.separator);
    public static final String WATER_MAIN_CONTROL_LOG_FILE_PATH = (Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "MainControl" + File.separator + "log" + File.separator + "mainControlLog" + File.separator);
    public static final String WATER_MAIN_CONTROL_MAP_FILE_PATH = (Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "MainControl" + File.separator + ScheduleFragment.MAP + File.separator + "water" + File.separator);
    public static final String WATER_MAKE_PLAN = "/api/make_plan";
    public static final String WATER_MOVE = "/api/move";
    public static final String WATER_NVR_CAPTURE_FILE_PATH = (Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "MainControl" + File.separator + "camera" + File.separator + "capture" + File.separator);
    public static final String WATER_NVR_LOG_FILE_PATH = (Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "MainControl" + File.separator + "log" + File.separator + "nvrLog" + File.separator);
    public static final String WATER_NVR_VIDEO_FILE_PATH = (Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "MainControl" + File.separator + "camera" + File.separator + FileConstant.VIDEO_FILE_NAME + File.separator);
    public static final String WATER_QUEDY_MARKER_BRIEF = "/api/markers/query_brief";
    public static final String WATER_QUEDY_MARKER_COUNT = "/api/markers/count";
    public static final String WATER_QUERY_MARKER_LIST = "/api/markers/query_list";
    public static final String WATER_REQUEST_DATA = "/api/request_data";
    public static final String WATER_ROBOT_INFO = "/api/robot_info";
    public static final String WATER_ROBOT_STATUS = "/api/robot_status";
    public static final String WATER_SCAN_WIFI = "/api/router/scan_wifi";
    public static final String WATER_SET_CURRENT_MAP = "/api/map/set_current_map";
    public static final String WATER_SET_PARAMS = "/api/set_params";
    public static final String WATER_SHUTDOWN = "/api/shutdown";
    public static final int WATER_UDP_CLOSE = 0;
    public static final String WATER_UDP_IP = "192.168.10.152";
    public static final int WATER_UDP_OPEN = 1;
    public static final int WATER_UDP_PORT = 7900;
    public static final String WATER_UPDATE_SOFTWARE = "/api/software/update";

    static {
        StringBuilder sb = new StringBuilder();
        sb.append(Environment.getExternalStorageDirectory().getAbsolutePath());
        sb.append(File.separator);
        sb.append("MainControl");
        sb.append(File.separator);
        sb.append("apk");
        sb.append(File.separator);
        WATER_MAIN_CONTROL_APK_FILE_PATH = sb.toString();
    }
}
